
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 118
#define YY_END_OF_BUFFER 119
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[383] =
    {   0,
        0,    0,    0,    0,    0,    0,  119,  117,   21,   23,
       20,   24,   19,   38,    9,  115,   43,  117,   47,   48,
       41,   39,   45,   40,  117,   42,  116,  116,   46,   36,
       37,   35,  115,  115,   51,   52,   44,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,   49,  117,   50,    6,    4,    5,    7,
        7,   18,   17,   17,   10,   18,   22,   27,  115,  115,
       33,   68,   69,   32,  113,    0,    1,    8,  114,    0,
        0,    0,  116,    0,   30,   29,   26,   28,   31,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,

      115,  115,   83,  115,  115,  115,  115,  115,  115,  115,
      115,   58,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,   34,    6,    3,    2,   16,   15,   13,   14,   11,
      113,    0,    0,    0,    8,    0,    0,  112,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,   89,
      115,  115,  115,   59,  115,  115,   97,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  110,  115,  115,  115,   12,    0,  113,

        0,    0,  114,  112,    0,  115,  115,  115,  115,  115,
      115,  115,   76,   77,  115,   79,  115,  115,  115,  115,
      115,   57,   84,  115,  115,  115,  115,   90,  115,  115,
      115,  115,   95,  115,   70,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  106,  115,  115,   25,
       66,  115,  115,  113,    0,    0,  114,    0,  115,  115,
      115,  115,  115,  115,   75,   78,   54,   80,  115,  115,
      115,  115,   86,   88,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  101,  115,  115,  103,  115,  115,
      107,  115,  115,   67,    0,  115,   65,   72,  115,   74,

      115,  115,  115,   56,  115,  115,  115,   92,  115,  115,
       96,  115,  115,  115,   62,   63,   64,  115,  104,  115,
      108,  115,  115,   55,   71,    0,  115,   53,  115,   82,
       85,   87,  115,  115,  115,   98,   99,  115,  115,  115,
      115,  115,    0,    0,   73,   81,  115,  115,  115,  115,
      102,  115,  115,  111,    0,    0,  115,  115,   94,  100,
      115,  109,    0,    0,   91,   93,  115,    0,    0,  115,
        0,    0,  105,    0,    0,    0,    0,    0,    0,   61,
       60,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,    9,    9,    9,    9,   26,    9,
        9,    9,   27,    9,    9,    9,    9,    9,    9,    9,
        9,    9,   28,    9,    9,    9,    9,    9,    9,    9,
       29,   30,   31,   32,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,    9,   43,   44,   45,   46,
       47,   48,    9,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[61] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    1,    3,    1,
        1,    1,    1,    4,    1,    1,    1,    1,    4,    3,
        3,    1,    1,    1,    1,    3,    3,    3,    1,    1,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[390] =
    {   0,
        0,    0,   58,   59,   62,   63,  280, 1114, 1114, 1114,
     1114,  263, 1114,  235, 1114,   54, 1114,  239, 1114, 1114,
     1114,  230, 1114,   59,   59,   67,   69,   78, 1114,   59,
      218,   76,   85,   88, 1114, 1114, 1114,   92,   94,  104,
       99,  108,  113,  102,  138,  115,  144,  146,  148,  150,
      167,  152,  169, 1114,  173, 1114,    0, 1114,  227,  204,
     1114, 1114, 1114,  218, 1114,  189, 1114, 1114,   97,    0,
     1114, 1114, 1114, 1114,  191,  180, 1114,    0,  155,  213,
      205,  194,  223,  227, 1114, 1114, 1114, 1114, 1114,  216,
      232,  234,  237,  242,  244,  248,  250,  252,  254,  256,

      258,  273,  262,  275,  277,  279,  287,  289,  285,  295,
      297,  299,  301,  303,  306,  313,  316,  318,  320,  325,
      322,  330,  338,  340,  345,  348,  355,  357,  362,  366,
      371, 1114,    0, 1114, 1114, 1114, 1114, 1114,  210, 1114,
      374,  400,  383,  163,    0,  407,  359,  405,  409,  377,
      411,  413,  415,  419,  421,  423,  428,  431,  425,  436,
      438,  448,  450,  452,  455,  457,  459,  463,  471,  473,
      478,  482,  486,  490,  492,  494,  496,  498,  500,  502,
      510,  513,  518,  520,  524,  526,  528,  530,  538,  532,
      542,  544,  556,  551,  558,  563,  565, 1114,  567,  571,

      167,  578,  580,  582,  585,  587,  590,  596,  599,  601,
      603,  608,  605,  610,  612,  617,  619,  622,  624,  626,
      635,  637,  639,  641,  643,  647,  650,  654,  656,  662,
      664,  668,  672,  675,  679,  682,  684,  686,  688,  692,
      694,  700,  702,  705,  711,  714,  716,  719,  728,  723,
      730,  732,  736,  738,  742,  154,  744,  746,  748,  740,
      761,  764,  767,  769,  771,  773,  775,  779,  781,  784,
      787,  789,  791,  793,  795,  799,  801,  803,  810,  812,
      816,  818,  823,  825,  835,  837,  840,  842,  844,  848,
      854,  856,  858,  860,  162,  862,  866,  872,  874,  868,

      881,  885,  887,  892,  894,  896,  898,  900,  903,  908,
      905,  910,  912,  914,  920,  925,  933,  935,  937,  939,
      941,  943,  946, 1114,  950,  153,  952,  955,  957,  959,
      962,  964,  967,  971,  976,  973,  978,  980,  984,  987,
      990,  996,  137,  127,  994,  999, 1001, 1003, 1005, 1007,
     1009, 1017, 1019, 1021,  140,  110, 1025, 1027, 1033, 1035,
     1037, 1040,  107,  135, 1042, 1044, 1047,   90,   84, 1051,
       92,   77, 1053,   94,   68,   51,   48,   40,   37, 1114,
     1114, 1114, 1094, 1098,   82, 1102, 1105,   66, 1109
    } ;

static const flex_int16_t yy_def[390] =
    {   0,
      382,    1,  383,  383,  384,  384,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  385,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  385,  385,  382,  382,  382,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  382,  382,  382,  386,  382,  382,  382,
      382,  382,  382,  382,  382,  387,  382,  382,  385,  388,
      382,  382,  382,  382,  382,  382,  382,  389,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,

      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  382,  386,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  389,  382,  382,  382,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  382,  382,  382,

      382,  382,  382,  382,  382,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  382,  382,  382,  382,  382,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  382,  385,  385,  385,  385,  385,

      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  382,  385,  382,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  382,  382,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  382,  382,  385,  385,  385,  385,
      385,  385,  382,  382,  385,  385,  385,  382,  382,  385,
      382,  382,  385,  382,  382,  382,  382,  382,  382,  382,
      382,    0,  382,  382,  382,  382,  382,  382,  382
    } ;

static const flex_int16_t yy_nxt[1175] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   16,   33,   34,   35,    8,
       36,   37,   16,   38,   39,   40,   41,   42,   43,   44,
       16,   45,   16,   46,   16,   47,   16,   48,   49,   50,
       51,   16,   52,   53,   16,   16,   16,   54,   55,   56,
       58,   58,   59,   59,   63,   63,   64,   64,   70,   65,
       65,   60,   60,   70,   70,   73,   61,   61,   75,   75,
       77,   85,   86,   74,   69,   78,   79,  381,   80,   80,
      380,   66,   66,  379,   81,   79,  378,   83,   83,   88,

       89,   82,   76,   81,   70,   70,   81,   70,   70,  377,
       84,   70,   70,   70,   70,   81,   70,   70,   70,   70,
      376,   70,   70,   70,   70,  375,   93,   70,   70,  374,
       90,  372,   70,   70,   70,   70,  102,   98,   91,  371,
       95,   94,   96,   92,   99,  103,  107,  100,  111,   97,
      101,  104,  369,  105,  108,  368,  109,   70,   70,  110,
      364,  115,  106,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,  363,   75,   75,  112,  116,  356,  119,
      146,  117,  113,  114,  355,  122,   70,   70,   70,   70,
      123,  138,  146,  139,  120,  118,  140,  121,  130,  344,

      124,  125,  324,  126,  295,  127,  256,  128,  201,  131,
      141,  141,  198,   80,   80,  129,  142,  144,  140,  147,
      136,  147,  135,  143,  148,  148,   82,  140,  142,  134,
       79,  132,   80,   80,  140,   70,   70,  140,   81,  140,
       79,   87,   83,   83,   72,   82,   83,   83,   81,   71,
       81,   70,   70,   70,   70,   84,   70,   70,   68,   84,
       81,   70,   70,   70,   70,   67,  149,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,  382,
      150,   70,   70,  151,  382,  155,  152,  159,  382,  160,
      154,  153,   70,   70,   70,   70,   70,   70,   70,   70,

      156,  157,  158,  161,   70,   70,   70,   70,   70,   70,
      382,  162,  382,  163,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,  164,   70,   70,  382,  165,  166,
      167,  169,   70,   70,  168,   70,   70,   70,   70,   70,
       70,   70,   70,  170,   70,   70,  382,  171,  172,   70,
       70,  175,  173,  174,  382,  179,  182,   70,   70,   70,
       70,  178,  382,  176,   70,   70,  180,   70,   70,  177,
      382,  181,  382,  185,   70,   70,   70,   70,  148,  148,
      183,   70,   70,  382,  184,   70,   70,  382,  186,  188,
       70,   70,  187,  141,  141,  192,   70,   70,  190,  142,

      189,  382,  141,  141,  382,  191,  143,  195,  382,  196,
      382,  142,  197,  193,  199,  143,  199,  194,  207,  200,
      200,  202,  382,  202,  204,  204,  203,  203,   70,   70,
       70,   70,   70,   70,   70,   70,  382,  205,   70,   70,
       70,   70,   70,   70,   70,   70,  206,   70,   70,  382,
       70,   70,  210,  382,  212,   70,   70,   70,   70,  382,
      213,  208,  211,  209,  382,  214,  215,   70,   70,   70,
       70,   70,   70,  216,   70,   70,   70,   70,   70,   70,
      382,  220,   70,   70,  221,  217,  382,  218,  219,  222,
       70,   70,   70,   70,  224,  382,  226,   70,   70,  223,

      382,   70,   70,  382,  227,   70,   70,  382,  225,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,  382,  228,  229,  382,  232,  230,   70,
       70,  233,   70,   70,  382,  234,  231,   70,   70,   70,
       70,  235,  236,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,  382,  237,  382,  239,   70,   70,  382,
      238,   70,   70,   70,   70,  244,  382,  243,  241,  240,
       70,   70,  382,  246,  242,   70,   70,   70,   70,  382,
      245,  247,   70,   70,   70,   70,  200,  200,  248,  249,
      254,  254,  382,  250,  251,  382,  252,  203,  203,  257,

      257,  204,  204,  255,  204,  204,   70,   70,  253,   70,
       70,  382,  258,  382,  205,   70,   70,  205,   70,   70,
       70,   70,   70,   70,   70,   70,  259,   70,   70,   70,
       70,   70,   70,  261,  382,  260,   70,   70,   70,   70,
      264,   70,   70,   70,   70,   70,   70,  262,  382,  263,
      265,  382,  266,  382,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,  382,  269,   70,   70,  267,   70,
       70,  382,  268,   70,   70,   70,   70,  270,  271,  382,
      250,   70,   70,   70,   70,  382,  272,   70,   70,  382,
      273,   70,   70,  275,   70,   70,  382,  277,   70,   70,

      274,   70,   70,   70,   70,   70,   70,   70,   70,  382,
      276,   70,   70,   70,   70,  280,  278,  281,  382,   70,
       70,   70,   70,  282,   70,   70,  382,  279,  382,  283,
       70,   70,  382,   70,   70,   70,   70,  287,   70,   70,
      284,  286,   70,   70,  285,  382,  289,   70,   70,   70,
       70,   70,   70,  288,  290,   70,   70,  254,  254,   70,
       70,  254,  254,  257,  257,  257,  257,   70,   70,  382,
      255,  382,  291,  294,  255,  382,  258,  292,  258,  297,
       70,   70,  293,   70,   70,  296,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,  382,  299,   70,   70,

       70,   70,  301,   70,   70,  298,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,  382,  300,   70,   70,
       70,   70,   70,   70,  304,  305,  302,  303,  382,   70,
       70,   70,   70,  382,  306,   70,   70,   70,   70,  307,
      382,  310,   70,   70,   70,   70,  309,  311,  382,  308,
      382,  312,  382,  314,   70,   70,   70,   70,  315,   70,
       70,   70,   70,   70,   70,  382,  313,   70,   70,  382,
      316,  382,  317,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,  382,  319,   70,   70,   70,   70,  326,
      318,   70,   70,   70,   70,  382,  320,  322,  382,  323,

       70,   70,  382,  321,   70,   70,   70,   70,  382,  327,
      325,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,  382,   70,   70,   70,   70,  328,   70,   70,   70,
       70,   70,   70,   70,   70,  333,  329,  330,  334,   70,
       70,  335,  382,  331,   70,   70,  382,  336,  382,  337,
      382,  332,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,  338,   70,   70,  343,  382,   70,
       70,   70,   70,  339,   70,   70,   70,   70,   70,   70,
      341,   70,   70,   70,   70,  340,   70,   70,  382,  342,
       70,   70,   70,   70,  346,   70,   70,   70,   70,   70,

       70,  382,  345,   70,   70,  382,   70,   70,  348,   70,
       70,  349,  347,   70,   70,   70,   70,  350,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
      382,  351,  352,  354,  382,  353,   70,   70,   70,   70,
       70,   70,  359,  360,   70,   70,   70,   70,  382,  358,
      382,  357,   70,   70,   70,   70,   70,   70,  361,   70,
       70,   70,   70,   70,   70,  366,   70,   70,  382,  362,
       70,   70,   70,   70,  365,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  370,  382,  382,  373,  382,  382,
      382,  382,  382,  367,   57,   57,   57,   57,   62,   62,

       62,   62,  133,  382,  133,  137,  137,  137,  137,  145,
      382,  145,  145,    7,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382
    } ;

static const flex_int16_t yy_chk[1175] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    3,    4,    5,    6,    5,    6,  388,    5,
        6,    3,    4,   16,   16,   24,    3,    4,   25,   25,
       26,   30,   30,   24,  385,   26,   27,  379,   27,   27,
      378,    5,    6,  377,   27,   28,  376,   28,   28,   32,

       32,   27,   25,   28,   33,   33,   27,   34,   34,  375,
       28,   38,   38,   39,   39,   28,   69,   69,   41,   41,
      374,   44,   44,   40,   40,  372,   38,   42,   42,  371,
       33,  369,   43,   43,   46,   46,   41,   40,   34,  368,
       39,   38,   39,   34,   40,   41,   43,   40,   44,   39,
       40,   42,  364,   42,   43,  363,   43,   45,   45,   43,
      356,   46,   42,   47,   47,   48,   48,   49,   49,   50,
       50,   52,   52,  355,   79,   79,   45,   47,  344,   48,
       79,   47,   45,   45,  343,   49,   51,   51,   53,   53,
       50,   66,   79,   66,   48,   47,   66,   48,   52,  326,

       50,   50,  295,   50,  256,   50,  201,   51,  144,   53,
       75,   75,  139,   82,   82,   51,   75,   76,   66,   81,
       64,   81,   60,   75,   81,   81,   82,   66,   75,   59,
       80,   55,   80,   80,   66,   90,   90,   66,   80,   66,
       83,   31,   83,   83,   22,   80,   84,   84,   83,   18,
       80,   91,   91,   92,   92,   83,   93,   93,   14,   84,
       83,   94,   94,   95,   95,   12,   90,   96,   96,   97,
       97,   98,   98,   99,   99,  100,  100,  101,  101,    7,
       91,  103,  103,   92,    0,   96,   93,   99,    0,  100,
       95,   94,  102,  102,  104,  104,  105,  105,  106,  106,

       97,   98,   98,  101,  109,  109,  107,  107,  108,  108,
        0,  102,    0,  103,  110,  110,  111,  111,  112,  112,
      113,  113,  114,  114,  104,  115,  115,    0,  105,  106,
      107,  109,  116,  116,  108,  117,  117,  118,  118,  119,
      119,  121,  121,  110,  120,  120,    0,  111,  113,  122,
      122,  115,  114,  114,    0,  119,  121,  123,  123,  124,
      124,  118,    0,  116,  125,  125,  120,  126,  126,  117,
        0,  120,    0,  124,  127,  127,  128,  128,  147,  147,
      122,  129,  129,    0,  123,  130,  130,    0,  124,  126,
      131,  131,  125,  141,  141,  129,  150,  150,  128,  141,

      127,    0,  143,  143,    0,  128,  141,  130,    0,  130,
        0,  141,  131,  129,  142,  143,  142,  129,  150,  142,
      142,  146,    0,  146,  148,  148,  146,  146,  149,  149,
      151,  151,  152,  152,  153,  153,    0,  148,  154,  154,
      155,  155,  156,  156,  159,  159,  149,  157,  157,    0,
      158,  158,  153,    0,  155,  160,  160,  161,  161,    0,
      156,  151,  154,  152,    0,  157,  158,  162,  162,  163,
      163,  164,  164,  159,  165,  165,  166,  166,  167,  167,
        0,  162,  168,  168,  163,  160,    0,  161,  161,  164,
      169,  169,  170,  170,  166,    0,  168,  171,  171,  165,

        0,  172,  172,    0,  169,  173,  173,    0,  167,  174,
      174,  175,  175,  176,  176,  177,  177,  178,  178,  179,
      179,  180,  180,    0,  171,  172,    0,  174,  172,  181,
      181,  175,  182,  182,    0,  176,  173,  183,  183,  184,
      184,  178,  179,  185,  185,  186,  186,  187,  187,  188,
      188,  190,  190,    0,  180,    0,  182,  189,  189,    0,
      181,  191,  191,  192,  192,  187,    0,  186,  184,  183,
      194,  194,    0,  189,  185,  193,  193,  195,  195,    0,
      188,  190,  196,  196,  197,  197,  199,  199,  191,  192,
      200,  200,    0,  193,  195,    0,  196,  202,  202,  203,

      203,  204,  204,  200,  205,  205,  206,  206,  197,  207,
      207,    0,  203,    0,  204,  208,  208,  205,  209,  209,
      210,  210,  211,  211,  213,  213,  206,  212,  212,  214,
      214,  215,  215,  208,    0,  207,  216,  216,  217,  217,
      211,  218,  218,  219,  219,  220,  220,  209,    0,  210,
      212,    0,  215,    0,  221,  221,  222,  222,  223,  223,
      224,  224,  225,  225,    0,  219,  226,  226,  217,  227,
      227,    0,  218,  228,  228,  229,  229,  220,  221,    0,
      225,  230,  230,  231,  231,    0,  224,  232,  232,    0,
      226,  233,  233,  229,  234,  234,    0,  231,  235,  235,

      227,  236,  236,  237,  237,  238,  238,  239,  239,    0,
      230,  240,  240,  241,  241,  236,  232,  237,    0,  242,
      242,  243,  243,  238,  244,  244,    0,  234,    0,  239,
      245,  245,    0,  246,  246,  247,  247,  243,  248,  248,
      240,  242,  250,  250,  241,    0,  245,  249,  249,  251,
      251,  252,  252,  244,  246,  253,  253,  254,  254,  260,
      260,  255,  255,  257,  257,  258,  258,  259,  259,    0,
      254,    0,  248,  253,  255,    0,  257,  249,  258,  260,
      261,  261,  252,  262,  262,  259,  263,  263,  264,  264,
      265,  265,  266,  266,  267,  267,    0,  262,  268,  268,

      269,  269,  264,  270,  270,  261,  271,  271,  272,  272,
      273,  273,  274,  274,  275,  275,    0,  263,  276,  276,
      277,  277,  278,  278,  271,  272,  269,  270,    0,  279,
      279,  280,  280,    0,  273,  281,  281,  282,  282,  275,
        0,  278,  283,  283,  284,  284,  277,  279,    0,  276,
        0,  280,    0,  282,  285,  285,  286,  286,  283,  287,
      287,  288,  288,  289,  289,    0,  281,  290,  290,    0,
      284,    0,  286,  291,  291,  292,  292,  293,  293,  294,
      294,  296,  296,    0,  289,  297,  297,  300,  300,  298,
      287,  298,  298,  299,  299,    0,  290,  292,    0,  293,

      301,  301,    0,  291,  302,  302,  303,  303,    0,  299,
      296,  304,  304,  305,  305,  306,  306,  307,  307,  308,
      308,    0,  309,  309,  311,  311,  301,  310,  310,  312,
      312,  313,  313,  314,  314,  307,  302,  303,  309,  315,
      315,  310,    0,  305,  316,  316,    0,  312,    0,  313,
        0,  306,  317,  317,  318,  318,  319,  319,  320,  320,
      321,  321,  322,  322,  314,  323,  323,  325,    0,  325,
      325,  327,  327,  318,  328,  328,  329,  329,  330,  330,
      322,  331,  331,  332,  332,  320,  333,  333,    0,  323,
      334,  334,  336,  336,  329,  335,  335,  337,  337,  338,

      338,    0,  327,  339,  339,    0,  340,  340,  334,  341,
      341,  335,  333,  345,  345,  342,  342,  338,  346,  346,
      347,  347,  348,  348,  349,  349,  350,  350,  351,  351,
        0,  339,  340,  342,    0,  341,  352,  352,  353,  353,
      354,  354,  349,  350,  357,  357,  358,  358,    0,  348,
        0,  347,  359,  359,  360,  360,  361,  361,  352,  362,
      362,  365,  365,  366,  366,  358,  367,  367,    0,  353,
      370,  370,  373,  373,  357,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  367,    0,    0,  370,    0,    0,
        0,    0,    0,  361,  383,  383,  383,  383,  384,  384,

      384,  384,  386,    0,  386,  387,  387,  387,  387,  389,
        0,  389,  389,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
/* 
 * Autores:
 * Simão Tomás Botas Carvalho - 2021223055
 * Teodoro Marques - 2023211717
 */
#line 8 "jucompiler.l"
   #include <stdio.h>
   #include <string.h>
   int line = 1;
   int column = 1;
   int print_tokens = 0;
   int comment_start_line = 1;
   int comment_start_col = 1;
   int string_start_line = 1;
   int string_start_col = 1;
   char string_buffer[10000];
   int buffer_pos = 0;
    int string_has_error = 0;
   
   void print_simple_token(const char *token) {
       if (print_tokens) {
           printf("%s\r\n", token);
       }
   }
   
   void print_valued_token(const char *token, const char *value) {
       if (print_tokens) {
           printf("%s(%s)\r\n", token, value);
       }
   }
#line 858 "lex.yy.c"

#line 860 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define STRING 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 44 "jucompiler.l"



#line 1083 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 383 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1114 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 47 "jucompiler.l"
{ BEGIN(COMMENT); comment_start_line = line; comment_start_col = column; column += 2; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 49 "jucompiler.l"
{ BEGIN(INITIAL); column += 2; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 50 "jucompiler.l"
{ line++; column = 1; }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 51 "jucompiler.l"
{ line++; column = 1; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 52 "jucompiler.l"
{ line++; column = 1; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 53 "jucompiler.l"
{ column += yyleng; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 54 "jucompiler.l"
{ column++; }
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 55 "jucompiler.l"
{ printf("Line %d, col %d: unterminated comment\r\n", comment_start_line, comment_start_col); yyterminate(); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 57 "jucompiler.l"
{ column += yyleng;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 59 "jucompiler.l"
{ BEGIN(STRING); string_start_line = line; string_start_col = column; buffer_pos = 0; string_has_error = 0; column++;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 "jucompiler.l"
{ 
    string_buffer[buffer_pos] = '\0';
    if (print_tokens && !string_has_error) printf("STRLIT(\"%s\")\r\n", string_buffer);
    BEGIN(INITIAL);
    column++;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 68 "jucompiler.l"
{ 
    string_buffer[buffer_pos++] = '\\';
    string_buffer[buffer_pos++] = yytext[1];
    column += yyleng;
}
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 74 "jucompiler.l"
{
    printf("Line %d, col %d: invalid escape sequence (\\)\r\n", line, column);
    printf("Line %d, col %d: unterminated string literal\r\n", string_start_line, string_start_col);
    line++;
    column = 1;
    BEGIN(INITIAL);
}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 82 "jucompiler.l"
{
    printf("Line %d, col %d: invalid escape sequence (\\)\r\n", line, column);
    printf("Line %d, col %d: unterminated string literal\r\n", string_start_line, string_start_col);
    line++;
    column = 1;
    BEGIN(INITIAL);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 90 "jucompiler.l"
{
    printf("Line %d, col %d: invalid escape sequence (\\)\r\n", line, column);
    printf("Line %d, col %d: unterminated string literal\r\n", string_start_line, string_start_col);
    line++;
    column = 1;
    BEGIN(INITIAL);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 98 "jucompiler.l"
{ 
    printf("Line %d, col %d: invalid escape sequence (%s)\r\n", line, column, yytext);
    string_has_error = 1;
    column += yyleng;
}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 104 "jucompiler.l"
{
    printf("Line %d, col %d: unterminated string literal\r\n", string_start_line, string_start_col);
    line++;
    column = 1;
    BEGIN(INITIAL);
}
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 111 "jucompiler.l"
{ 
    printf("Line %d, col %d: unterminated string literal\r\n", string_start_line, string_start_col);
    line++;
    column = 1;
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 118 "jucompiler.l"
{ 
    printf("Line %d, col %d: unterminated string literal\r\n", string_start_line, string_start_col);
    yyterminate();
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 123 "jucompiler.l"
{
    string_buffer[buffer_pos++] = yytext[0];
    column++;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 129 "jucompiler.l"
{column++; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 130 "jucompiler.l"
{column += yyleng; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 131 "jucompiler.l"
{column += yyleng; }
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 133 "jucompiler.l"
{ line++; column = 1;}
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 134 "jucompiler.l"
{ line++; column = 1;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 135 "jucompiler.l"
{ line++; column = 1;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 138 "jucompiler.l"
{ print_valued_token("BOOLLIT", yytext); column += yyleng; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 139 "jucompiler.l"
{ print_simple_token("EQ"); column += yyleng; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 140 "jucompiler.l"
{ print_simple_token("NE"); column += yyleng; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 141 "jucompiler.l"
{ print_simple_token("GE"); column += yyleng; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 142 "jucompiler.l"
{ print_simple_token("LE"); column += yyleng; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 143 "jucompiler.l"
{ print_simple_token("LSHIFT"); column += yyleng; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 144 "jucompiler.l"
{ print_simple_token("RSHIFT"); column += yyleng; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 145 "jucompiler.l"
{ print_simple_token("ARROW"); column += yyleng; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 146 "jucompiler.l"
{ print_simple_token("AND"); column += yyleng; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 147 "jucompiler.l"
{ print_simple_token("OR"); column += yyleng; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 148 "jucompiler.l"
{ print_simple_token("GT"); column += yyleng; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 149 "jucompiler.l"
{ print_simple_token("LT"); column += yyleng; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 150 "jucompiler.l"
{ print_simple_token("ASSIGN"); column += yyleng; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 151 "jucompiler.l"
{ print_simple_token("NOT"); column += yyleng; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 152 "jucompiler.l"
{ print_simple_token("PLUS"); column += yyleng; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 153 "jucompiler.l"
{ print_simple_token("MINUS"); column += yyleng; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 154 "jucompiler.l"
{ print_simple_token("STAR"); column += yyleng; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 155 "jucompiler.l"
{ print_simple_token("DIV"); column += yyleng; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 156 "jucompiler.l"
{ print_simple_token("MOD"); column += yyleng; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 157 "jucompiler.l"
{ print_simple_token("XOR"); column += yyleng; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 158 "jucompiler.l"
{ print_simple_token("COMMA"); column += yyleng; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 159 "jucompiler.l"
{ print_simple_token("SEMICOLON"); column += yyleng; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 160 "jucompiler.l"
{ print_simple_token("LPAR"); column += yyleng; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 161 "jucompiler.l"
{ print_simple_token("RPAR"); column += yyleng; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 162 "jucompiler.l"
{ print_simple_token("LBRACE"); column += yyleng; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 163 "jucompiler.l"
{ print_simple_token("RBRACE"); column += yyleng; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 164 "jucompiler.l"
{ print_simple_token("LSQ"); column += yyleng; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 165 "jucompiler.l"
{ print_simple_token("RSQ"); column += yyleng; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 170 "jucompiler.l"
{ print_simple_token("BOOL"); column += yyleng; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 171 "jucompiler.l"
{ print_simple_token("CLASS"); column += yyleng; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 172 "jucompiler.l"
{ print_simple_token("DOTLENGTH"); column += yyleng; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 173 "jucompiler.l"
{ print_simple_token("DOUBLE"); column += yyleng; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 174 "jucompiler.l"
{ print_simple_token("ELSE"); column += yyleng; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 175 "jucompiler.l"
{ print_simple_token("IF"); column += yyleng; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 176 "jucompiler.l"
{ print_simple_token("INT"); column += yyleng; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 177 "jucompiler.l"
{ print_simple_token("PRINT"); column += yyleng; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 178 "jucompiler.l"
{ print_simple_token("PARSEINT"); column += yyleng; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 179 "jucompiler.l"
{ print_simple_token("PUBLIC"); column += yyleng; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 180 "jucompiler.l"
{ print_simple_token("RETURN"); column += yyleng; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 181 "jucompiler.l"
{ print_simple_token("STATIC"); column += yyleng; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 182 "jucompiler.l"
{ print_simple_token("STRING"); column += yyleng; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 183 "jucompiler.l"
{ print_simple_token("VOID"); column += yyleng; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 184 "jucompiler.l"
{ print_simple_token("WHILE"); column += yyleng; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 186 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 187 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 188 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 189 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 190 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 191 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 192 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 193 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 194 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 195 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 196 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 197 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 198 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 199 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 200 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 201 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 202 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 203 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 204 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 205 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 206 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 207 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 208 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 209 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 210 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 211 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 212 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 213 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 214 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 215 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 216 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 217 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 218 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 219 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 220 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 221 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 222 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 223 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 224 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 225 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 226 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 227 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 228 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 229 "jucompiler.l"
{ print_valued_token("RESERVED", yytext); column += yyleng; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 234 "jucompiler.l"
{ print_valued_token("DECIMAL", yytext); column += yyleng; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 235 "jucompiler.l"
{ print_valued_token("DECIMAL", yytext); column += yyleng; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 236 "jucompiler.l"
{ print_valued_token("DECIMAL", yytext); column += yyleng; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 238 "jucompiler.l"
{ print_valued_token("IDENTIFIER", yytext); column += yyleng; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 239 "jucompiler.l"
{ print_valued_token("NATURAL", yytext); column += yyleng; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 242 "jucompiler.l"
{ printf("Line %d, col %d: illegal character (%s)\r\n", line, column, yytext); column += yyleng; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 244 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1793 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 383 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 383 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 382);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 244 "jucompiler.l"

extern int yylex();
int main(int argc, char *argv[]) {
    if (argc > 1) {
        if (strcmp(argv[1], "-l") == 0) {
            print_tokens = 1;
        } else if (strcmp(argv[1], "-e1") == 0) {
            print_tokens = 0;
        }
    } else {
        print_tokens = 0;
    }
    yylex();
    return 0;
}

