
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 116
#define YY_END_OF_BUFFER 117
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[382] =
    {   0,
        0,    0,    0,    0,    0,    0,  117,  115,   19,   21,
       22,   36,    9,  113,   41,  115,   45,   46,   39,   37,
       43,   38,  115,   40,  114,  114,   44,   34,   35,   33,
      113,  113,   49,   50,   42,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,   47,  115,   48,    6,    4,    5,    7,    7,   18,
       17,   17,   10,   18,   19,   20,   25,  113,  113,   31,
       66,   67,   30,  111,    0,    1,    8,  112,    0,    0,
        0,  114,    0,   28,   27,   24,   26,   29,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,

      113,   81,  113,  113,  113,  113,  113,  113,  113,  113,
       56,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
       32,    6,    3,    2,   16,   15,   13,   14,   11,  111,
        0,    0,    0,    8,    0,    0,  110,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,   87,  113,
      113,  113,   57,  113,  113,   95,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  108,  113,  113,  113,   12,    0,  111,    0,

        0,  112,  110,    0,  113,  113,  113,  113,  113,  113,
      113,   74,   75,  113,   77,  113,  113,  113,  113,  113,
       55,   82,  113,  113,  113,  113,   88,  113,  113,  113,
      113,   93,  113,   68,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  104,  113,  113,   23,   64,
      113,  113,  111,    0,    0,  112,    0,  113,  113,  113,
      113,  113,  113,   73,   76,   52,   78,  113,  113,  113,
      113,   84,   86,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,   99,  113,  113,  101,  113,  113,  105,
      113,  113,   65,    0,  113,   63,   70,  113,   72,  113,

      113,  113,   54,  113,  113,  113,   90,  113,  113,   94,
      113,  113,  113,   60,   61,   62,  113,  102,  113,  106,
      113,  113,   53,   69,    0,  113,   51,  113,   80,   83,
       85,  113,  113,  113,   96,   97,  113,  113,  113,  113,
      113,    0,    0,   71,   79,  113,  113,  113,  113,  100,
      113,  113,  109,    0,    0,  113,  113,   92,   98,  113,
      107,    0,    0,   89,   91,  113,    0,    0,  113,    0,
        0,  103,    0,    0,    0,    0,    0,    0,   59,   58,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,    7,    7,    7,    7,   24,    7,
        7,    7,   25,    7,    7,    7,    7,    7,    7,    7,
        7,    7,   26,    7,    7,    7,    7,    7,    7,    7,
       27,   28,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,    7,   41,   42,   43,   44,
       45,   46,    7,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   57,   58,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    2,    2,    1,    1,    3,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    4,    3,    3,    1,
        1,    1,    1,    3,    3,    3,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[389] =
    {   0,
        0,    0,   56,   58,   60,   68,  251, 1119,  242, 1119,
      232,  209, 1119,   58, 1119,  213, 1119, 1119, 1119,  204,
     1119,   63,   61,   70,   73,   82, 1119,   62,  193,   71,
       89,   92, 1119, 1119, 1119,   96,   98,  108,  103,  112,
      117,  106,  142,  119,  148,  150,  152,  154,  171,  156,
      173, 1119,  154, 1119,    0, 1119,  206,  190, 1119, 1119,
     1119,  202, 1119,  210,  200, 1119, 1119,  101,    0, 1119,
     1119, 1119, 1119,  201,  163, 1119,    0,  159,  205,  215,
      208,  224,  227, 1119, 1119, 1119, 1119, 1119,  231,  234,
      243,  245,  247,  249,  251,  253,  255,  257,  260,  264,

      278,  266,  280,  282,  287,  291,  293,  295,  299,  301,
      303,  305,  307,  316,  312,  320,  323,  325,  329,  334,
      339,  344,  352,  357,  360,  362,  364,  373,  367,  375,
     1119,    0, 1119, 1119, 1119, 1119, 1119,  193, 1119,  377,
      399,  379,  150,    0,  406,  410,  412,  414,  416,  418,
      420,  422,  426,  428,  430,  434,  443,  436,  445,  453,
      455,  457,  460,  462,  467,  470,  476,  479,  473,  481,
      488,  491,  495,  497,  501,  503,  505,  509,  518,  524,
      520,  526,  530,  533,  535,  538,  540,  545,  542,  547,
      549,  552,  562,  565,  567,  576, 1119,  578,  583,  149,

      585,  588,  590,  592,  594,  597,  606,  608,  610,  612,
      615,  617,  619,  621,  625,  627,  631,  633,  635,  640,
      643,  645,  647,  650,  652,  658,  660,  665,  669,  671,
      674,  677,  679,  681,  686,  690,  692,  694,  696,  701,
      705,  707,  713,  717,  719,  721,  728,  730,  734,  736,
      738,  743,  745,  750,  132,  752,  754,  748,  756,  770,
      772,  774,  777,  779,  781,  783,  787,  789,  792,  796,
      800,  798,  802,  806,  808,  810,  818,  812,  820,  823,
      825,  827,  832,  834,  844,  846,  848,  850,  852,  855,
      861,  864,  866,  137,  868,  872,  878,  874,  887,  891,

      893,  895,  898,  900,  902,  904,  906,  908,  913,  910,
      915,  918,  920,  928,  931,  934,  939,  941,  943,  945,
      947,  949, 1119,  954,  118,  956,  959,  961,  963,  966,
      968,  971,  974,  977,  980,  982,  984,  988,  994,  998,
      990,  112,  105, 1000, 1003, 1005, 1010, 1012, 1014, 1017,
     1021, 1025, 1027,  110,   85, 1032, 1034, 1038, 1040, 1044,
     1046,   85,  112, 1048, 1050, 1054,   75,   66, 1057,   69,
       55, 1059,   74,   55,   46,   41,   32,   20, 1119, 1119,
     1119, 1099, 1103,   64, 1107, 1110,   62, 1114
    } ;

static const flex_int16_t yy_def[389] =
    {   0,
      381,    1,  382,  382,  383,  383,  381,  381,  381,  381,
      381,  381,  381,  384,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      384,  384,  381,  381,  381,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  381,  381,  381,  385,  381,  381,  381,  381,  381,
      381,  381,  381,  386,  381,  381,  381,  384,  387,  381,
      381,  381,  381,  381,  381,  381,  388,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,

      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      381,  385,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  388,  381,  381,  381,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  381,  381,  381,  381,

      381,  381,  381,  381,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  381,  381,  381,  381,  381,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  381,  384,  384,  384,  384,  384,  384,

      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  381,  384,  381,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  381,  381,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  381,  381,  384,  384,  384,  384,  384,
      384,  381,  381,  384,  384,  384,  381,  381,  384,  381,
      381,  384,  381,  381,  381,  381,  381,  381,  381,  381,
        0,  381,  381,  381,  381,  381,  381,  381
    } ;

static const flex_int16_t yy_nxt[1178] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   14,   31,   32,   33,    8,   34,   35,
       14,   36,   37,   38,   39,   40,   41,   42,   14,   43,
       14,   44,   14,   45,   14,   46,   47,   48,   49,   14,
       50,   51,   14,   14,   14,   52,   53,   54,   56,   57,
       56,   57,   61,   62,   69,   63,   68,   58,  380,   58,
       61,   62,   59,   63,   59,   69,   69,   72,   74,   74,
      379,   76,   84,   85,  378,   73,   77,   64,   78,  377,
       79,   79,   87,   88,  376,   64,   80,   78,  375,   82,

       82,  374,   75,   81,  373,   80,   69,   69,   80,   69,
       69,  371,   83,   69,   69,   69,   69,   80,   69,   69,
       69,   69,  370,   69,   69,   69,   69,  368,   92,   69,
       69,  367,   89,  363,   69,   69,   69,   69,  101,   97,
       90,  362,   94,   93,   95,   91,   98,  102,  106,   99,
      110,   96,  100,  103,  355,  104,  107,  354,  108,   69,
       69,  109,  343,  114,  105,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,  323,   74,   74,  111,  115,
      294,  118,  145,  116,  112,  113,  255,  121,   69,   69,
       69,   69,  122,  200,  145,  197,  119,  117,  143,  120,

      129,   65,  123,  124,  135,  125,  134,  126,  133,  127,
      131,  130,  137,  138,   86,  139,   71,  128,  140,  140,
       78,   70,   79,   79,  141,   79,   79,  146,   80,  146,
       67,  142,  147,  147,   66,   81,  141,  139,   81,   78,
       80,   82,   82,   65,   82,   82,  139,   80,   69,   69,
      381,   69,   69,  139,   83,  381,  139,   83,  139,   80,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,  381,   69,   69,  148,
      149,   69,   69,   69,   69,  381,  154,  381,  158,  381,
      150,  159,  151,  153,  152,   69,   69,   69,   69,   69,

       69,  155,  156,  157,   69,   69,  381,  160,   69,   69,
       69,   69,   69,   69,  161,  162,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,  381,  163,  381,   69,
       69,  164,  166,   69,   69,  165,  167,   69,   69,  168,
       69,   69,   69,   69,  381,  169,   69,   69,  381,  170,
      171,   69,   69,  381,  172,  173,   69,   69,  178,  174,
      175,   69,   69,  381,  177,  381,  181,  381,  179,   69,
       69,  176,  381,  180,   69,   69,  381,   69,   69,   69,
       69,   69,   69,  184,   69,   69,  381,  182,  183,  381,
       69,   69,   69,   69,  140,  140,  140,  140,  185,  187,

      141,  381,  186,  189,  191,  188,  194,  142,  195,  142,
      190,  198,  141,  198,  196,  381,  199,  199,  201,  381,
      201,  381,  192,  202,  202,  381,  193,  147,  147,  203,
      203,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,  381,  204,   69,   69,   69,   69,   69,   69,  205,
      381,   69,   69,   69,   69,  206,  381,  209,  381,  211,
       69,   69,   69,   69,  381,  212,  207,  210,  208,  213,
       69,   69,   69,   69,   69,   69,  214,   69,   69,   69,
       69,  381,  215,  381,   69,   69,  219,   69,   69,  220,
       69,   69,  216,   69,   69,  221,   69,   69,   69,   69,

      217,  218,  223,  381,  222,   69,   69,  225,   69,   69,
      226,  381,   69,   69,   69,   69,  381,  224,   69,   69,
       69,   69,   69,   69,  381,  227,   69,   69,  381,  228,
      231,  381,  229,  381,  232,   69,   69,   69,   69,  230,
      233,   69,   69,   69,   69,  381,  234,   69,   69,  235,
       69,   69,   69,   69,  381,   69,   69,   69,   69,   69,
       69,  238,   69,   69,   69,   69,   69,   69,  236,   69,
       69,  381,  237,  243,  242,  239,  240,  381,  245,   69,
       69,  241,   69,   69,   69,   69,  381,  249,  244,  246,
      381,  247,  248,   69,   69,  199,  199,  381,  251,  250,

      253,  253,  202,  202,  381,  256,  256,  203,  203,  203,
      203,   69,   69,  254,   69,   69,  381,  252,  257,  381,
      204,  381,  204,   69,   69,   69,   69,   69,   69,   69,
       69,  258,   69,   69,   69,   69,   69,   69,   69,   69,
      259,  260,   69,   69,   69,   69,  381,  263,   69,   69,
       69,   69,   69,   69,  261,  264,  262,   69,   69,  265,
       69,   69,   69,   69,   69,   69,  381,   69,   69,   69,
       69,  381,  268,  381,  266,   69,   69,   69,   69,  267,
      381,  270,   69,   69,  269,  249,   69,   69,   69,   69,
      271,   69,   69,  272,   69,   69,   69,   69,   69,   69,

      274,  381,  276,   69,   69,  381,  273,   69,   69,   69,
       69,   69,   69,   69,   69,  275,  381,  279,   69,   69,
      277,  280,   69,   69,   69,   69,  381,  281,  381,  278,
       69,   69,  381,  282,   69,   69,   69,   69,   69,   69,
      286,  381,  283,  381,  285,   69,   69,   69,   69,  284,
      288,   69,   69,   69,   69,   69,   69,  289,  381,  287,
       69,   69,  253,  253,  381,   69,   69,  253,  253,  256,
      256,  256,  256,   69,   69,  254,  381,  291,  293,  290,
      254,  381,  257,  295,  257,  381,  292,   69,   69,   69,
       69,   69,   69,  296,   69,   69,   69,   69,   69,   69,

       69,   69,  381,  298,   69,   69,   69,   69,  300,   69,
       69,  381,  297,   69,   69,   69,   69,   69,   69,   69,
       69,  381,  299,   69,   69,   69,   69,   69,   69,   69,
       69,  303,  301,  302,  304,   69,   69,   69,   69,  305,
       69,   69,   69,   69,   69,   69,  381,  310,  306,   69,
       69,   69,   69,  308,  309,  381,  307,  311,  313,  381,
      314,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,  312,   69,   69,  381,  315,  381,  316,   69,   69,
      381,   69,   69,   69,   69,   69,   69,  381,  318,   69,
       69,   69,   69,  325,  317,   69,   69,  381,  319,  381,

      321,  381,  320,  322,   69,   69,  381,  326,   69,   69,
       69,   69,   69,   69,  324,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,  381,
       69,   69,   69,   69,  327,   69,   69,   69,   69,  332,
      381,  333,  328,  329,  334,   69,   69,  330,   69,   69,
      335,   69,   69,  336,  381,  331,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,  337,  342,
      381,   69,   69,   69,   69,  338,   69,   69,   69,   69,
       69,   69,  340,   69,   69,   69,   69,  339,   69,   69,
      341,   69,   69,  381,   69,   69,  345,   69,   69,   69,

       69,   69,   69,  381,  344,   69,   69,   69,   69,  347,
      348,   69,   69,  381,  346,   69,   69,   69,   69,  349,
       69,   69,   69,   69,  381,  353,  381,   69,   69,   69,
       69,   69,   69,  350,   69,   69,  381,  351,   69,   69,
      381,  352,   69,   69,   69,   69,  381,  358,  359,   69,
       69,   69,   69,  356,  357,   69,   69,   69,   69,  381,
      360,   69,   69,   69,   69,   69,   69,   69,   69,  381,
      365,   69,   69,  361,   69,   69,   69,   69,  381,  364,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  369,
      381,  372,  381,  381,  381,  381,  381,  381,  366,   55,

       55,   55,   55,   60,   60,   60,   60,  132,  381,  132,
      136,  136,  136,  136,  144,  381,  144,  144,    7,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381
    } ;

static const flex_int16_t yy_chk[1178] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        4,    4,    5,    5,  387,    5,  384,    3,  378,    4,
        6,    6,    3,    6,    4,   14,   14,   22,   23,   23,
      377,   24,   28,   28,  376,   22,   24,    5,   25,  375,
       25,   25,   30,   30,  374,    6,   25,   26,  373,   26,

       26,  371,   23,   25,  370,   26,   31,   31,   25,   32,
       32,  368,   26,   36,   36,   37,   37,   26,   68,   68,
       39,   39,  367,   42,   42,   38,   38,  363,   36,   40,
       40,  362,   31,  355,   41,   41,   44,   44,   39,   38,
       32,  354,   37,   36,   37,   32,   38,   39,   41,   38,
       42,   37,   38,   40,  343,   40,   41,  342,   41,   43,
       43,   41,  325,   44,   40,   45,   45,   46,   46,   47,
       47,   48,   48,   50,   50,  294,   78,   78,   43,   45,
      255,   46,   78,   45,   43,   43,  200,   47,   49,   49,
       51,   51,   48,  143,   78,  138,   46,   45,   75,   46,

       50,   65,   48,   48,   62,   48,   58,   48,   57,   49,
       53,   51,   64,   64,   29,   64,   20,   49,   74,   74,
       79,   16,   79,   79,   74,   81,   81,   80,   79,   80,
       12,   74,   80,   80,   11,   79,   74,   64,   81,   82,
       79,   82,   82,    9,   83,   83,   64,   82,   89,   89,
        7,   90,   90,   64,   82,    0,   64,   83,   64,   82,
       91,   91,   92,   92,   93,   93,   94,   94,   95,   95,
       96,   96,   97,   97,   98,   98,    0,   99,   99,   89,
       90,  100,  100,  102,  102,    0,   95,    0,   98,    0,
       91,   99,   92,   94,   93,  101,  101,  103,  103,  104,

      104,   96,   97,   97,  105,  105,    0,  100,  106,  106,
      107,  107,  108,  108,  101,  102,  109,  109,  110,  110,
      111,  111,  112,  112,  113,  113,    0,  103,    0,  115,
      115,  104,  106,  114,  114,  105,  107,  116,  116,  108,
      117,  117,  118,  118,    0,  109,  119,  119,    0,  110,
      112,  120,  120,    0,  113,  113,  121,  121,  118,  114,
      115,  122,  122,    0,  117,    0,  120,    0,  119,  123,
      123,  116,    0,  119,  124,  124,    0,  125,  125,  126,
      126,  127,  127,  123,  129,  129,    0,  121,  122,    0,
      128,  128,  130,  130,  140,  140,  142,  142,  123,  125,

      140,    0,  124,  127,  128,  126,  129,  140,  129,  142,
      127,  141,  140,  141,  130,    0,  141,  141,  145,    0,
      145,    0,  128,  145,  145,    0,  128,  146,  146,  147,
      147,  148,  148,  149,  149,  150,  150,  151,  151,  152,
      152,    0,  147,  153,  153,  154,  154,  155,  155,  148,
        0,  156,  156,  158,  158,  149,    0,  152,    0,  154,
      157,  157,  159,  159,    0,  155,  150,  153,  151,  156,
      160,  160,  161,  161,  162,  162,  157,  163,  163,  164,
      164,    0,  158,    0,  165,  165,  161,  166,  166,  162,
      169,  169,  159,  167,  167,  163,  168,  168,  170,  170,

      160,  160,  165,    0,  164,  171,  171,  167,  172,  172,
      168,    0,  173,  173,  174,  174,    0,  166,  175,  175,
      176,  176,  177,  177,    0,  170,  178,  178,    0,  171,
      173,    0,  171,    0,  174,  179,  179,  181,  181,  172,
      175,  180,  180,  182,  182,    0,  177,  183,  183,  178,
      184,  184,  185,  185,    0,  186,  186,  187,  187,  189,
      189,  181,  188,  188,  190,  190,  191,  191,  179,  192,
      192,    0,  180,  186,  185,  182,  183,    0,  188,  193,
      193,  184,  194,  194,  195,  195,    0,  192,  187,  189,
        0,  190,  191,  196,  196,  198,  198,    0,  195,  194,

      199,  199,  201,  201,    0,  202,  202,  203,  203,  204,
      204,  205,  205,  199,  206,  206,    0,  196,  202,    0,
      203,    0,  204,  207,  207,  208,  208,  209,  209,  210,
      210,  205,  211,  211,  212,  212,  213,  213,  214,  214,
      206,  207,  215,  215,  216,  216,    0,  210,  217,  217,
      218,  218,  219,  219,  208,  211,  209,  220,  220,  214,
      221,  221,  222,  222,  223,  223,    0,  224,  224,  225,
      225,    0,  218,    0,  216,  226,  226,  227,  227,  217,
        0,  220,  228,  228,  219,  224,  229,  229,  230,  230,
      223,  231,  231,  225,  232,  232,  233,  233,  234,  234,

      228,    0,  230,  235,  235,    0,  226,  236,  236,  237,
      237,  238,  238,  239,  239,  229,    0,  235,  240,  240,
      231,  236,  241,  241,  242,  242,    0,  237,    0,  233,
      243,  243,    0,  238,  244,  244,  245,  245,  246,  246,
      242,    0,  239,    0,  241,  247,  247,  248,  248,  240,
      244,  249,  249,  250,  250,  251,  251,  245,    0,  243,
      252,  252,  253,  253,    0,  258,  258,  254,  254,  256,
      256,  257,  257,  259,  259,  253,    0,  248,  252,  247,
      254,    0,  256,  258,  257,    0,  251,  260,  260,  261,
      261,  262,  262,  259,  263,  263,  264,  264,  265,  265,

      266,  266,    0,  261,  267,  267,  268,  268,  263,  269,
      269,    0,  260,  270,  270,  272,  272,  271,  271,  273,
      273,    0,  262,  274,  274,  275,  275,  276,  276,  278,
      278,  270,  268,  269,  271,  277,  277,  279,  279,  272,
      280,  280,  281,  281,  282,  282,    0,  278,  274,  283,
      283,  284,  284,  276,  277,    0,  275,  279,  281,    0,
      282,  285,  285,  286,  286,  287,  287,  288,  288,  289,
      289,  280,  290,  290,    0,  283,    0,  285,  291,  291,
        0,  292,  292,  293,  293,  295,  295,    0,  288,  296,
      296,  298,  298,  297,  286,  297,  297,    0,  289,    0,

      291,    0,  290,  292,  299,  299,    0,  298,  300,  300,
      301,  301,  302,  302,  295,  303,  303,  304,  304,  305,
      305,  306,  306,  307,  307,  308,  308,  310,  310,    0,
      309,  309,  311,  311,  300,  312,  312,  313,  313,  306,
        0,  308,  301,  302,  309,  314,  314,  304,  315,  315,
      311,  316,  316,  312,    0,  305,  317,  317,  318,  318,
      319,  319,  320,  320,  321,  321,  322,  322,  313,  324,
        0,  324,  324,  326,  326,  317,  327,  327,  328,  328,
      329,  329,  321,  330,  330,  331,  331,  319,  332,  332,
      322,  333,  333,    0,  334,  334,  328,  335,  335,  336,

      336,  337,  337,    0,  326,  338,  338,  341,  341,  333,
      334,  339,  339,    0,  332,  340,  340,  344,  344,  337,
      345,  345,  346,  346,    0,  341,    0,  347,  347,  348,
      348,  349,  349,  338,  350,  350,    0,  339,  351,  351,
        0,  340,  352,  352,  353,  353,    0,  348,  349,  356,
      356,  357,  357,  346,  347,  358,  358,  359,  359,    0,
      351,  360,  360,  361,  361,  364,  364,  365,  365,    0,
      357,  366,  366,  352,  369,  369,  372,  372,    0,  356,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  366,
        0,  369,    0,    0,    0,    0,    0,    0,  360,  382,

      382,  382,  382,  383,  383,  383,  383,  385,    0,  385,
      386,  386,  386,  386,  388,    0,  388,  388,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
/*
 * Autores:
 * Simão Tomás Botas Carvalho - 2021223055
 * Teodoro Marques - 2023211717
 */
#line 8 "jucompiler.l"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

/* Header gerado por yacc/bison a partir do jucompiler.y.
 * (o teu Makefile deve gerar y.tab.h) */
#include "y.tab.h"

/* Executado antes de cada ação do lexer:
 * guarda a posição inicial do token em syn_* e avança a coluna. */
#define YY_USER_ACTION { syn_line = lex_line; syn_column = lex_column; lex_column += yyleng; }

/* Para tokens com valor (IDENTIFIER, NATURAL, DECIMAL, BOOLLIT, STRLIT, etc.)
 * assume-se que o %union no yacc tem o campo 'lexeme'. */
#define PASS_TOKEN() yylval.lexeme = strdup(yytext)

int lex_line = 1;
int lex_column = 1;
int syn_line = -1;
int syn_column = -1;

int print_tokens = 0;

int comment_start_line = 1;
int comment_start_col = 1;
int string_start_line = 1;
int string_start_col = 1;
char string_buffer[10000];
int buffer_pos = 0;
int string_has_error = 0;

static void print_simple_token(const char *token) {
    if (print_tokens) {
        printf("%s\n", token);
    }
}

static void print_valued_token(const char *token, const char *value) {
    if (print_tokens) {
        printf("%s(%s)\n", token, value);
    }
}

#line 878 "lex.yy.c"

#line 880 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define STR 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 63 "jucompiler.l"



#line 1103 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 382 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1119 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 66 "jucompiler.l"
{ comment_start_line = syn_line; comment_start_col = syn_column; BEGIN(COMMENT); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 68 "jucompiler.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 69 "jucompiler.l"
{ lex_line++; lex_column = 1; }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 70 "jucompiler.l"
{ lex_line++; lex_column = 1; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 71 "jucompiler.l"
{ lex_line++; lex_column = 1; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 72 "jucompiler.l"
{ ; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 73 "jucompiler.l"
{ ; }
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 74 "jucompiler.l"
{ printf("Line %d, col %d: unterminated comment\n", comment_start_line, comment_start_col); yyterminate(); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 76 "jucompiler.l"
{ ; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 78 "jucompiler.l"
{ BEGIN(STR); string_start_line = syn_line; string_start_col = syn_column; buffer_pos = 0; string_has_error = 0; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 80 "jucompiler.l"
{
    string_buffer[buffer_pos] = '\0';
    if (print_tokens && !string_has_error) printf("STRLIT(\"%s\")\n", string_buffer);
    yylval.lexeme = strdup(string_buffer);
    BEGIN(INITIAL);
    return STRLIT;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 88 "jucompiler.l"
{ 
    string_buffer[buffer_pos++] = '\\';
    string_buffer[buffer_pos++] = yytext[1];
}
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 93 "jucompiler.l"
{
    printf("Line %d, col %d: invalid escape sequence (\\)\n", syn_line, syn_column);
    printf("Line %d, col %d: unterminated string literal\n", string_start_line, string_start_col);
    lex_line++;
    lex_column = 1;
    BEGIN(INITIAL);
}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 101 "jucompiler.l"
{
    printf("Line %d, col %d: invalid escape sequence (\\)\n", syn_line, syn_column);
    printf("Line %d, col %d: unterminated string literal\n", string_start_line, string_start_col);
    lex_line++;
    lex_column = 1;
    BEGIN(INITIAL);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 109 "jucompiler.l"
{
    printf("Line %d, col %d: invalid escape sequence (\\)\n", syn_line, syn_column);
    printf("Line %d, col %d: unterminated string literal\n", string_start_line, string_start_col);
    lex_line++;
    lex_column = 1;
    BEGIN(INITIAL);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 117 "jucompiler.l"
{ 
    printf("Line %d, col %d: invalid escape sequence (%s)\n", syn_line, syn_column, yytext);
    string_has_error = 1;
}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 122 "jucompiler.l"
{
    printf("Line %d, col %d: unterminated string literal\n", string_start_line, string_start_col);
    lex_line++;
    lex_column = 1;
    BEGIN(INITIAL);
}
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 129 "jucompiler.l"
{ 
    printf("Line %d, col %d: unterminated string literal\n", string_start_line, string_start_col);
    lex_line++;
    lex_column = 1;
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(STR):
#line 136 "jucompiler.l"
{ 
    printf("Line %d, col %d: unterminated string literal\n", string_start_line, string_start_col);
    yyterminate();
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 141 "jucompiler.l"
{
    string_buffer[buffer_pos++] = yytext[0];
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 146 "jucompiler.l"
{ ; }
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 148 "jucompiler.l"
{ lex_line++; lex_column = 1; }
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 149 "jucompiler.l"
{ lex_line++; lex_column = 1; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 150 "jucompiler.l"
{ lex_line++; lex_column = 1; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 153 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("BOOLLIT", yytext); return BOOLLIT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 154 "jucompiler.l"
{ print_simple_token("EQ"); return EQ; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 155 "jucompiler.l"
{ print_simple_token("NE"); return NE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 156 "jucompiler.l"
{ print_simple_token("GE"); return GE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 157 "jucompiler.l"
{ print_simple_token("LE"); return LE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 158 "jucompiler.l"
{ print_simple_token("LSHIFT"); return LSHIFT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 159 "jucompiler.l"
{ print_simple_token("RSHIFT"); return RSHIFT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 160 "jucompiler.l"
{ print_simple_token("ARROW"); return ARROW; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 161 "jucompiler.l"
{ print_simple_token("AND"); return AND; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 162 "jucompiler.l"
{ print_simple_token("OR"); return OR; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 163 "jucompiler.l"
{ print_simple_token("GT"); return GT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 164 "jucompiler.l"
{ print_simple_token("LT"); return LT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 165 "jucompiler.l"
{ print_simple_token("ASSIGN"); return ASSIGN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 166 "jucompiler.l"
{ print_simple_token("NOT"); return NOT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 167 "jucompiler.l"
{ print_simple_token("PLUS"); return PLUS; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 168 "jucompiler.l"
{ print_simple_token("MINUS"); return MINUS; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 169 "jucompiler.l"
{ print_simple_token("STAR"); return STAR; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 170 "jucompiler.l"
{ print_simple_token("DIV"); return DIV; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 171 "jucompiler.l"
{ print_simple_token("MOD"); return MOD; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 172 "jucompiler.l"
{ print_simple_token("XOR"); return XOR; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 173 "jucompiler.l"
{ print_simple_token("COMMA"); return COMMA; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 174 "jucompiler.l"
{ print_simple_token("SEMICOLON"); return SEMICOLON; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 175 "jucompiler.l"
{ print_simple_token("LPAR"); return LPAR; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 176 "jucompiler.l"
{ print_simple_token("RPAR"); return RPAR; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 177 "jucompiler.l"
{ print_simple_token("LBRACE"); return LBRACE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 178 "jucompiler.l"
{ print_simple_token("RBRACE"); return RBRACE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 179 "jucompiler.l"
{ print_simple_token("LSQ"); return LSQ; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 180 "jucompiler.l"
{ print_simple_token("RSQ"); return RSQ; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 184 "jucompiler.l"
{ print_simple_token("BOOL"); return BOOL; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 185 "jucompiler.l"
{ print_simple_token("CLASS"); return CLASS; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 186 "jucompiler.l"
{ print_simple_token("DOTLENGTH"); return DOTLENGTH; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 187 "jucompiler.l"
{ print_simple_token("DOUBLE"); return DOUBLE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 188 "jucompiler.l"
{ print_simple_token("ELSE"); return ELSE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 189 "jucompiler.l"
{ print_simple_token("IF"); return IF; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 190 "jucompiler.l"
{ print_simple_token("INT"); return INT; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 191 "jucompiler.l"
{ print_simple_token("PRINT"); return PRINT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 192 "jucompiler.l"
{ print_simple_token("PARSEINT"); return PARSEINT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 193 "jucompiler.l"
{ print_simple_token("PUBLIC"); return PUBLIC; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 194 "jucompiler.l"
{ print_simple_token("RETURN"); return RETURN; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 195 "jucompiler.l"
{ print_simple_token("STATIC"); return STATIC; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 196 "jucompiler.l"
{ print_simple_token("STRING"); return STRING; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 197 "jucompiler.l"
{ print_simple_token("VOID"); return VOID; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 198 "jucompiler.l"
{ print_simple_token("WHILE"); return WHILE; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 200 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 201 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 202 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 203 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 204 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 205 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 206 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 207 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 208 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 209 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 210 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 211 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 212 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 213 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 214 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 215 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 216 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 217 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 218 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 219 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 220 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 221 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 222 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 223 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 224 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 225 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 226 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 227 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 228 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 229 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 230 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 231 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 232 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 233 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 234 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 235 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 236 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 237 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 238 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 239 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 240 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 241 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 242 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 243 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("RESERVED", yytext); return RESERVED; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 246 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("DECIMAL", yytext); return DECIMAL; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 247 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("DECIMAL", yytext); return DECIMAL; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 248 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("DECIMAL", yytext); return DECIMAL; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 250 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("IDENTIFIER", yytext); return IDENTIFIER; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 251 "jucompiler.l"
{ PASS_TOKEN(); print_valued_token("NATURAL", yytext); return NATURAL; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 253 "jucompiler.l"
{ printf("Line %d, col %d: illegal character (%s)\n", syn_line, syn_column, yytext); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 255 "jucompiler.l"
{ YY_USER_ACTION; return 0; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 257 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1805 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 382 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 382 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 381);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 257 "jucompiler.l"



